scrape_configs:
  - job_name: "Product Service"
    metrics_path: '/actuator/prometheus'
    scrape_interval: 1s
    static_configs:
      - targets: [ '192.168.18.6:9091' ]
      - labels:
          application: 'Product Service Microservice'

  - job_name: "Client Service"
    metrics_path: '/actuator/prometheus'
    scrape_interval: 1s
    static_configs:
      - targets: [ '192.168.18.6:9005' ]
      - labels:
          application: 'Client Service Microservice'

  - job_name: "User Service"
    metrics_path: '/actuator/prometheus'
    scrape_interval: 1s
    static_configs:
      - targets: [ '192.168.18.6:9010' ]
      - labels:
          application: 'User Service Microservice'