scrape_configs:
  - job_name: "Product Service"
    metrics_path: '/actuator/prometheus'
    scrape_interval: 1s
    static_configs:
      - targets: ['192.168.1.123:9091','192.168.1.123:9092']
      - labels:
          application: 'Product Service Microservice'