version: "3.9"
services:
  #  mongo-service:
  #    image: mongo
  #    container_name: mitocode-mongo-service
  #    ports:
  #      - 27017:27017 #Puerto externo:Puerto interno
  #    environment:
  #      MONGO_INITDB_ROOT_USERNAME: mitocode
  #      MONGO_INITDB_ROOT_PASSWORD: mitocode
  #    networks:
  #      - mitocode
  #
  #
  #  mongo-express:
  #    image: mongo-express
  #    container_name: mitocode-mongo-express
  #    ports:
  #      - 8081:8081
  #    environment:
  #      ME_CONFIG_MONGODB_ADMINUSERNAME: mitocode
  #      ME_CONFIG_MONGODB_ADMINPASSWORD: mitocode
  #      ME_CONFIG_MONGODB_URL: mongodb://mitocode:mitocode@mongo-service:27017
  #    networks:
  #      - mitocode
  #
  #  mysql:
  #    image: mysql:latest
  #    container_name: mitocode-mysql
  #    volumes:
  #      - mysql-keycloak:/var/lib/mysql
  #    environment:
  #      MYSQL_ROOT_PASSWORD: root_mitocode
  #      MYSQL_DATABASE: keycloak
  #      MYSQL_USER: admin
  #      MYSQL_PASSWORD: mitocode
  #    ports:
  #      - 3306:3306
  #    networks:
  #      - mitocode

  #  keycloak:
  #    image: quay.io/keycloak/keycloak:19.0.1
  #    container_name: mitocode-keycloak
  #    environment:
  #      KEYCLOAK_ADMIN: admin
  #      KEYCLOAK_ADMIN_PASSWORD: admin
  #      KC_DB: mysql
  #      KC_DB_USERNAME: admin
  #      KC_DB_PASSWORD: mitocode
  #      KC_DB_URL_HOST: mysql
  #      KC_DB_URL_PORT: 3306
  #      KC_DB_SCHEMA: keycloak
  #    ports:
  #      - 8080:8080
  #    depends_on: [mysql]
  #    command: start-dev
  #    networks:
  #      - mitocode

  zipkin:
    image: ghcr.io/openzipkin/zipkin-slim
    container_name: mitocode-zipkin
    environment:
      - STORAGE_TYPE=mem
    ports:
      - 9411:9411
    networks:
      - mitocode

  prometheus:
    image: prom/prometheus
    container_name: mitocode-prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/config/:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - mitocode

  grafana:
    image: grafana/grafana-oss
    container_name: mitocode-grafana
    ports:
      - 3000:3000
    volumes:
      - ./grafana/:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SERVER_DOMAIN=localhost
    networks:
      - mitocode

  loki:
    image: grafana/loki
    container_name: mitocode_loki
    ports:
      - 3100:3100
    networks:
      - mitocode

  zoopeker:
    image: confluentinc/cp-zookeeper
    container_name: mitocode-kafka-zookeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181
    networks:
      - mitocode

  broker:
    image: confluentinc/cp-kafka
    container_name: mitocode-kafka-broker
    ports:
      - 9092:9092
    depends_on:
      - zoopeker
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 192.168.18.6:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT, PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092, PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_REPLICATION_FACTOR: 1
    networks:
      - mitocode

  mongo-query-service:
    image: mongo
    container_name: mitocode-mongo-query-service
    ports:
      - 27018:27017 #Puerto externo:Puerto interno
    environment:
      MONGO_INITDB_ROOT_USERNAME: mitocode
      MONGO_INITDB_ROOT_PASSWORD: mitocode
    networks:
      - mitocode


  mongo-query-express:
    image: mongo-express
    container_name: mitocode-mongo-query-express
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mitocode
      ME_CONFIG_MONGODB_ADMINPASSWORD: mitocode
      ME_CONFIG_MONGODB_URL: mongodb://mitocode:mitocode@mongo-query-service:27017
    networks:
      - mitocode

volumes:
  mysql-keycloak:

networks:
  mitocode:
    name: mitocode-network